name: Dependency Submission

on:
  push:
    branches: [ 'main' ]

permissions:
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Generate and submit dependency graph
      env: 
        ORG_GRADLE_PROJECT_artifactory_user: ${{ secrets.artifactory_user }}
        ORG_GRADLE_PROJECT_artifactory_password: ${{ secrets.artifactory_password }}
        ORG_GRADLE_PROJECT_artifactory_contextUrl: ${{ secrets.artifactory_contextUrl }}
        DEPENDENCY_GRAPH_INCLUDE_CONFIGURATIONS: 'runtimeClasspath'
      uses: gradle/actions/dependency-submission@v3
